# --- FONT ---
# Usiamo il Nerd Font che abbiamo scaricato per le icone
font_family      FiraCode Nerd Font
bold_font        auto
italic_font      auto
bold_italic_font auto
font_size        13.0

# --- REGOLAZIONE GEOMETRIA FONT ---
# Stringe o allarga la spaziatura orizzontale dei caratteri (100% è il default)
modify_font cell_width 100%

# Stringe o allarga la spaziatura verticale (line-height)
modify_font cell_height 100%

# --- TRASPARENZA E FINESTRA ---
# Qui picom entra in gioco. Cambia lo 0.85 a piacimento (1.0 è opaco)
background_opacity         0.85
dynamic_background_opacity yes

# Margini interni per non avere il testo appiccicato ai bordi dello schermo
window_padding_width 10

# --- COLORI (Catppuccin Macchiato) ---
foreground            #CAD3F5
background            #24273A
selection_foreground  #24273A
selection_background  #F4DBD6

# I 16 colori standard del terminale
color0 #494D64
color8 #5B6078
color1 #ED8796
color9 #ED8796
color2 #A6DA95
color10 #A6DA95
color3 #EED49F
color11 #EED49F
color4 #8AADF4
color12 #8AADF4
color5 #F5BDE6
color13 #F5BDE6
color6 #8BD5CA
color14 #8BD5CA
color7 #B8C0E0
color15 #A5ADCB

# Colore del cursore
cursor                #F4DBD6
cursor_text_color     #24273A

# --- PERFORMANCE E PREFERENZE ---
# Disabilita il fastidioso suono acustico di errore
enable_audio_bell no

# Rendi i link internet cliccabili con Ctrl + Click
detect_urls yes
url_color #8AADF4

# Stile del cursore (beam è la barretta verticale, altrimenti usa block)
cursor_shape beam